name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: github-pages
    
    steps:
      - uses: actions/checkout@v3

      - name: Create config.js
        run: |
          cat > config.js << 'EOF'
          const CONFIG = {
              ASSEMBLYAI: {
                  API_KEY: '${{ secrets.ASSEMBLYAI_API_KEY }}',
                  UPLOAD_URL: '${{ secrets.ASSEMBLYAI_UPLOAD_URL }}',
                  TRANSCRIPT_URL: '${{ secrets.ASSEMBLYAI_TRANSCRIPT_URL }}',
                  LANGUAGE_CODE: 'ar',
                  SETTINGS: {
                      speaker_labels: true,
                      punctuate: true,
                      format_text: true,
                      language_code: 'ar'
                  }
              },
              JSONBIN: {
                  API_KEY: '${{ secrets.JSONBIN_API_KEY }}',
                  BASE_URL: '${{ secrets.JSONBIN_BASE_URL }}'
              },
              APP: {
                  WEB_APP_URL: '${{ secrets.WEB_APP_URL }}',
                  MAX_FILE_SIZE: 52428800,
                  ALLOWED_AUDIO_FORMATS: ['audio/mpeg', 'audio/wav', 'audio/ogg', 'audio/m4a', 'audio/flac', 'audio/mp3'],
                  MAX_TEXT_LENGTH: 100000,
                  AUTO_SAVE_INTERVAL: 30000
              },
              TELEGRAM: {
                  USER_ID: '${{ secrets.TELEGRAM_USER_ID }}'
              },
              TEMPLATES: {
                  COUNT: 4,
                  COLORS_PER_TEMPLATE: 4,
                  TOTAL_IMAGES: 16
              },
              SERIES_COLORS: [
                  '#667eea', '#f5576c', '#4facfe', '#43e97b',
                  '#fa709a', '#feca57', '#ff6348', '#2c3e50'
              ]
          };
          if (typeof module !== 'undefined' && module.exports) {
              module.exports = CONFIG;
          }
          EOF

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          force_orphan: true
