name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Inject secrets into config.js
        run: |
          sed -i "s|const TELEGRAM_USER_ID = .*;|const TELEGRAM_USER_ID = '${{ secrets.TELEGRAM_USER_ID }}';|g" config.js
          sed -i "s|const ASSEMBLYAI_API_KEY = .*;|const ASSEMBLYAI_API_KEY = '${{ secrets.ASSEMBLYAI_API_KEY }}';|g" config.js
          sed -i "s|const ASSEMBLYAI_UPLOAD_URL = .*;|const ASSEMBLYAI_UPLOAD_URL = '${{ secrets.ASSEMBLYAI_UPLOAD_URL }}';|g" config.js
          sed -i "s|const ASSEMBLYAI_TRANSCRIPT_URL = .*;|const ASSEMBLYAI_TRANSCRIPT_URL = '${{ secrets.ASSEMBLYAI_TRANSCRIPT_URL }}';|g" config.js
          sed -i "s|const JSONBIN_API_KEY = .*;|const JSONBIN_API_KEY = '${{ secrets.JSONBIN_API_KEY }}';|g" config.js
          sed -i "s|const JSONBIN_BASE_URL = .*;|const JSONBIN_BASE_URL = '${{ secrets.JSONBIN_BASE_URL }}';|g" config.js
          sed -i "s|const WEB_APP_URL = .*;|const WEB_APP_URL = '${{ secrets.WEB_APP_URL }}';|g" config.js
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
